//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectX.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeDescription_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeDescription_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectX.Entities.Resources.CodeDescription-English", typeof(CodeDescription_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong! Please Check Later..
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed Succesfully.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Policy Number.
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Profile Name.
        /// </summary>
        internal static string _1100 {
            get {
                return ResourceManager.GetString("1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Profile Type.
        /// </summary>
        internal static string _1101 {
            get {
                return ResourceManager.GetString("1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact Name.
        /// </summary>
        internal static string _1102 {
            get {
                return ResourceManager.GetString("1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country.
        /// </summary>
        internal static string _1103 {
            get {
                return ResourceManager.GetString("1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Linked To Fees.
        /// </summary>
        internal static string _1104 {
            get {
                return ResourceManager.GetString("1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Linked Adherent.
        /// </summary>
        internal static string _1105 {
            get {
                return ResourceManager.GetString("1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Linked To Case.
        /// </summary>
        internal static string _1106 {
            get {
                return ResourceManager.GetString("1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Linked To GOP.
        /// </summary>
        internal static string _1107 {
            get {
                return ResourceManager.GetString("1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Call Detected.
        /// </summary>
        internal static string _1200 {
            get {
                return ResourceManager.GetString("1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Closed.
        /// </summary>
        internal static string _1201 {
            get {
                return ResourceManager.GetString("1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Proceed Not Accepted Case.
        /// </summary>
        internal static string _1202 {
            get {
                return ResourceManager.GetString("1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Open Non-Closed Case.
        /// </summary>
        internal static string _1203 {
            get {
                return ResourceManager.GetString("1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Not Allowed.
        /// </summary>
        internal static string _1204 {
            get {
                return ResourceManager.GetString("1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Approval Needed.
        /// </summary>
        internal static string _1205 {
            get {
                return ResourceManager.GetString("1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Report Required.
        /// </summary>
        internal static string _1206 {
            get {
                return ResourceManager.GetString("1206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Medical Case.
        /// </summary>
        internal static string _1207 {
            get {
                return ResourceManager.GetString("1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Required.
        /// </summary>
        internal static string _1208 {
            get {
                return ResourceManager.GetString("1208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Approved.
        /// </summary>
        internal static string _1209 {
            get {
                return ResourceManager.GetString("1209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reason.
        /// </summary>
        internal static string _1210 {
            get {
                return ResourceManager.GetString("1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Partner.
        /// </summary>
        internal static string _1211 {
            get {
                return ResourceManager.GetString("1211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Has No Valid Email!.
        /// </summary>
        internal static string _1212 {
            get {
                return ResourceManager.GetString("1212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Branch.
        /// </summary>
        internal static string _1213 {
            get {
                return ResourceManager.GetString("1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Already Consumed.
        /// </summary>
        internal static string _1300 {
            get {
                return ResourceManager.GetString("1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Too Large.
        /// </summary>
        internal static string _1400 {
            get {
                return ResourceManager.GetString("1400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Detected.
        /// </summary>
        internal static string _1401 {
            get {
                return ResourceManager.GetString("1401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string _1402 {
            get {
                return ResourceManager.GetString("1402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email Failed.
        /// </summary>
        internal static string _1500 {
            get {
                return ResourceManager.GetString("1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Required.
        /// </summary>
        internal static string _1501 {
            get {
                return ResourceManager.GetString("1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Required.
        /// </summary>
        internal static string _1502 {
            get {
                return ResourceManager.GetString("1502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Required.
        /// </summary>
        internal static string _1503 {
            get {
                return ResourceManager.GetString("1503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Attachments.
        /// </summary>
        internal static string _1504 {
            get {
                return ResourceManager.GetString("1504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout, Try Again...
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Format.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        internal static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string _502 {
            get {
                return ResourceManager.GetString("502", resourceCulture);
            }
        }
    }
}
